# Файл docker-compose.yml

# Версия docker-compose
version: '3'

# Перечень volume
volumes:
  pg_data:
  static:
  media:

# Перечень контейнеров
services:
 # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер БД
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13

    # Файл (или список файлов) с переменными окружения 
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/data
      
      
  # Имя и описание контейнера с бэкендом
  backend:
    build: ./backend/
    env_file: .env
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/app/media


  # Имя третьего контейнера. Это контейнер с фронтендом
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - gateway
#    command: cp -r /app/build/. /static/


# Добавляем новый контейнер: gateway.
  gateway:
    # Сбилдить и запустить образ, 
    # описанный в Dockerfile в папке nginx
    build: ./nginx/
    env_file: .env
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 9000 хоста
    # на порт 80 контейнера.
    
    depends_on:
      - backend
      
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media
